FROM python:3.10-slim

WORKDIR /app

COPY docker/requirements-tracker.txt ./requirements-tracker.txt
RUN pip install --no-cache-dir -r requirements-tracker.txt

# Copy code
COPY kafka/ ./kafka/
COPY collector/ ./collector/

# Ensure Python can import kafka.* and collector.*
ENV PYTHONPATH=/app

CMD ["python", "kafka/tracker.py"]
